version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /build
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tests/docker
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /tests
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /perf-tests
    schedule:
      interval: weekly


  - package-ecosystem: npm
    directory: /docs/_vendor/gitlab.com/f5/nginx/controller/poc/f5-hugo
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /docs
    schedule:
      interval: daily
