name: Fossa

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '**.md'

concurrency:
  group: ${{ github.ref_name }}-fossa
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:

  scan:
    name: Fossa
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Scan
        uses: fossas/fossa-action@f61a4c0c263690f2ddb54b9822a719c25a7b608f # v1.3.1
        with:
          api-key: ${{ secrets.FOSSA_TOKEN }}
