name: Sync labels

on:
  schedule:
    - cron: '8 0 * * 1' # run every Monday at 00:08 UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}-sync
  cancel-in-progress: true

jobs:
  # This job sync the labels across the various repos
  labels-sync:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.fork == false }}
    strategy:
      fail-fast: false
      matrix:
        repo:
          - nginxinc/kubernetes-ingress
          - nginxinc/nginx-ingress-helm-operator
          - nginxinc/nginx-prometheus-exporter
          - nginxinc/nginx-plus-go-client
          - nginxinc/nginx-asg-sync
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Sync Labels
        uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.NGINX_PAT }}
          prune: true
